name: RC Tag Terraform Module Publisher

on:
  push:
    tags:
      - '0.0.0-terraform-*'  # Matches RC tags created by workflow 1

jobs:
  call-release-workflow:
    uses: shabbir-saifee-cmm/delivery-workflows/.github/workflows/terraform-release-candidate.yaml@main
    with:
      releaseName: ${{ github.ref_name }}
      artifactConfig: |
        terraform:
          hcp-terraform:
            moduleName: hcp-terraform
            modulePath: ./terraform/hcp-terraform
            moduleProvider: tfe
    # secrets:
    #   MCK_CMM_HCP_TERRAFORM_TOKEN: ${{ secrets.MCK_CMM_HCP_TERRAFORM_TOKEN }}
