name: RC Tag Terraform Module Publisher

on:
  workflow_run:
    workflows: ["Handle Ready-to-Test Comments"]  # Name of Workflow 1
    types:
      - completed

jobs:
  get-tag:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.get-tag.outputs.tag_name }}
    steps:
      - name: Get latest RC tag
        id: get-tag
        uses: actions/github-script@v6
        with:
          script: |
            // Get the latest RC tag created around the time of the workflow
            const { data: tags } = await github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 10
            });

            // Find the most recent RC tag
            const rcTag = tags.find(tag => tag.name.startsWith('0.0.0-terraform-') && tag.name.includes('-rc'));

            if (!rcTag) {
              core.setFailed('No RC tag found');
              return;
            }

            core.setOutput('tag_name', rcTag.name);
            core.info(`Found RC tag: ${rcTag.name}`);

jobs:
  call-release-workflow:
    uses: shabbir-saifee-cmm/delivery-workflows/.github/workflows/terraform-release-candidate.yaml@main
    with:
      tagName: ${{ github.ref_name }}
      artifactConfig: |
        terraform:
          hcp-terraform:
            moduleName: hcp-terraform
            modulePath: ./terraform/hcp-terraform
            moduleProvider: tfe
    secrets:
      MCK_CMM_HCP_TERRAFORM_TOKEN: 'test'
