name: Handle Ready-to-Test Comments

on:
  issue_comment:
    types: [created]

jobs:
  create-rc-tag:
    if: >
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, 'ready-to-test-terraform-')
    uses: shabbir-saifee-cmm/delivery-workflows/.github/workflows/terraform-release-candidate-tag.yaml@main
