name: Terraform release candidate automation

on:
  issue_comment:
    types: [created]

jobs:
  terraform-rc-pipeline:
    if: >
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, 'ready-to-test-terraform-')
    permissions:
      contents: write
      pull-requests: write
      actions: write
    uses: shabbir-saifee-cmm/delivery-workflows/.github/workflows/terraform-rc-automation.yaml@main
    secrets:
      TF_AUTOMATION_APP_SECRET: ${{ secrets.TF_AUTOMATION_APP_SECRET }}
      TF_AUTOMATION_APP_ID: ${{ secrets.TF_AUTOMATION_APP_ID }}
      # MCK_CMM_HCP_TERRAFORM_TOKEN: ${{ secrets.MCK_CMM_HCP_TERRAFORM_TOKEN }}
